# Generated by Django 6.0.3 on 2026-03-22 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookentry',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='webhookentry',
            name='processing_result',
        ),
    ]
