# Generated by Django 6.0.3 on 2026-03-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='configuration',
        ),
    ]
