# Generated by Django 6.0.3 on 2026-03-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='cost',
            field=models.PositiveIntegerField(default=0, help_text='Costo en créditos de ElevenLabs'),
        ),
        migrations.AddField(
            model_name='call',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='call',
            name='termination_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
